//! Notification types delivered to the consumer via broadcast channel.
//!
//! When the read-loop receives a JSON-RPC message without an `id`, it parses
//! the `method` field and constructs a `Notification`, which is sent through
//! a `tokio::sync::broadcast` to any subscriber who called `client.notifications()`.

use serde::Deserialize;

/// A server-initiated notification delivered to the client.
///
/// Generated by the read-loop from incoming JSON-RPC messages that have no `id`
/// (i.e. notifications). A special `Disconnected` variant is emitted when the
/// transport closes, so consumers can clean up.
///
/// This enum is `#[non_exhaustive]`: new notification variants may be added
/// in SemVer-compatible releases. Use a wildcard `_` arm in `match` statements.
///
/// # Example
///
/// ```rust,no_run
/// # use stand_in_client::notification::Notification;
/// # use tokio::sync::broadcast;
/// # async fn example(rx: &mut broadcast::Receiver<Notification>) {
/// match rx.recv().await {
///     Ok(Notification::ResourcesUpdated { uri }) => println!("{} changed", uri),
///     Ok(Notification::Disconnected) => println!("transport closed"),
///     _ => {}  // required because Notification is #[non_exhaustive]
/// }
/// # }
/// ```
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub enum Notification {
    /// A resource has been updated. The `uri` identifies the changed resource.
    ResourcesUpdated {
        /// URI of the updated resource.
        uri: String,
    },

    /// The list of available resources has changed.
    ResourcesListChanged,

    /// The list of available tools has changed.
    ToolsListChanged,

    /// The transport was closed (EOF or error).
    /// Consumers should stop awaiting notifications.
    Disconnected,

    /// An unrecognised notification method was received.
    /// The method name and params are preserved for forward compatibility.
    Other {
        /// The JSON-RPC method name.
        method: String,
        /// The notification parameters.
        params: serde_json::Value,
    },
}

/// Parsed raw notification body from an incoming JSON-RPC notification frame.
#[derive(Debug, Deserialize)]
struct RawNotification {
    #[allow(dead_code)]
    jsonrpc: String,
    method: String,
    #[serde(default)]
    params: Option<serde_json::Value>,
}

/// Parameters for `notifications/resources/updated` notifications.
#[derive(Debug, Deserialize)]
struct ResourcesUpdatedParams {
    uri: String,
}

impl Notification {
    /// Parse a JSON-RPC notification value into a `Notification`.
    ///
    /// The value must have a `method` field. Returns `None` if the method
    /// cannot be deserialized (should be logged and skipped by the caller).
    pub(crate) fn from_value(value: &serde_json::Value) -> Option<Self> {
        let raw: RawNotification = serde_json::from_value(value.clone()).ok()?;

        match raw.method.as_str() {
            "notifications/resources/updated" => {
                if let Some(ref p) = raw.params
                    && let Ok(up) = serde_json::from_value::<ResourcesUpdatedParams>(p.clone())
                {
                    return Some(Self::ResourcesUpdated { uri: up.uri });
                }
                Some(Self::ResourcesUpdated { uri: String::new() })
            }
            "notifications/resources/list_changed" => Some(Self::ResourcesListChanged),
            "notifications/tools/list_changed" => Some(Self::ToolsListChanged),
            _ => Some(Self::Other {
                method: raw.method,
                params: raw.params.unwrap_or(serde_json::Value::Null),
            }),
        }
    }

    /// Create a disconnection notification (transport EOF or error).
    pub(crate) fn disconnected() -> Self {
        Self::Disconnected
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_notification_is_send_sync() {
        fn assert_send_sync<T: Send + Sync>() {}
        assert_send_sync::<Notification>();
    }

    #[test]
    fn test_resources_updated_parsing() {
        let value = serde_json::json!({
            "jsonrpc": "2.0",
            "method": "notifications/resources/updated",
            "params": { "uri": "file:///changed.txt" }
        });
        let n = Notification::from_value(&value).unwrap();
        assert_eq!(
            n,
            Notification::ResourcesUpdated {
                uri: "file:///changed.txt".into()
            }
        );
    }

    #[test]
    fn test_resources_updated_missing_params() {
        let value = serde_json::json!({
            "jsonrpc": "2.0",
            "method": "notifications/resources/updated"
        });
        let n = Notification::from_value(&value).unwrap();
        assert_eq!(n, Notification::ResourcesUpdated { uri: String::new() });
    }

    #[test]
    fn test_resources_list_changed() {
        let value = serde_json::json!({
            "jsonrpc": "2.0",
            "method": "notifications/resources/list_changed"
        });
        let n = Notification::from_value(&value).unwrap();
        assert_eq!(n, Notification::ResourcesListChanged);
    }

    #[test]
    fn test_tools_list_changed() {
        let value = serde_json::json!({
            "jsonrpc": "2.0",
            "method": "notifications/tools/list_changed"
        });
        let n = Notification::from_value(&value).unwrap();
        assert_eq!(n, Notification::ToolsListChanged);
    }

    #[test]
    fn test_unknown_notification() {
        let value = serde_json::json!({
            "jsonrpc": "2.0",
            "method": "custom/event",
            "params": { "data": 42 }
        });
        let n = Notification::from_value(&value).unwrap();
        match n {
            Notification::Other { method, params } => {
                assert_eq!(method, "custom/event");
                assert_eq!(params, serde_json::json!({ "data": 42 }));
            }
            _ => panic!("expected Other variant"),
        }
    }

    #[test]
    fn test_disconnected() {
        let n = Notification::disconnected();
        assert_eq!(n, Notification::Disconnected);
    }
}
