//! MCP client example: the `#[mcp_client]` macro (typed stubs).
//!
//! Run:
//!   cargo run -p stand-in-client --example typed_client
//!
//! This example is **self-contained**: it spins up an in-process MCP server
//! via `stand-in`'s own macros, then connects a typed client generated by
//! `#[mcp_client]` — all in one process.
//!
//! Demonstrates:
//! - Defining a trait with `#[mcp_client]` to get typed stubs
//! - `String` return detection (text extraction)
//! - Non-`String` return deserialization (`i64` via `from_str`)
//! - `#[tool(name = "...")]` override for tool name mapping
//! - `isError` → `Err(Error::ToolError(...))` collapse in the typed layer
//! - `Pub trait` compatibility (the macro emits `#[allow(async_fn_in_trait)]`)
//! - `ExampleApiClient::new()` / `.client()` / `.into_inner()` API

#![cfg(feature = "http")]

use std::net::SocketAddr;
use std::time::Duration;

use stand_in::error::Result as ServerResult;
use stand_in::prelude::*;

use stand_in_client::prelude::*;
use stand_in_client::transport::HttpTransport as ClientHttpTransport;

// ---------------------------------------------------------------------------
// Inline MCP server (self-contained)
// ---------------------------------------------------------------------------

#[mcp_tool(name = "greet", description = "Greet someone by name")]
async fn greet(name: String) -> ServerResult<String> {
    Ok(format!("Hello, {name}!"))
}

#[mcp_tool(name = "add", description = "Add two integers")]
async fn add(a: i64, b: i64) -> ServerResult<String> {
    Ok(format!("{}", a + b))
}

#[mcp_tool(
    name = "divide",
    description = "Divide two integers (returns error on zero divisor)"
)]
async fn divide(a: i64, b: i64) -> ServerResult<String> {
    if b == 0 {
        Err(stand_in::error::Error::ToolError("division by zero".into()))
    } else {
        Ok(format!("{}", a / b))
    }
}

#[mcp_server(host = "127.0.0.1", port = 0)]
struct TypedExampleServer;

// ---------------------------------------------------------------------------
// Typed client trait — the `#[mcp_client]` macro
// ---------------------------------------------------------------------------

/// Typed client for the inline example server.
///
/// `pub trait` exercises the `#[allow(async_fn_in_trait)]` path (the macro
/// re-emits the trait with that attribute so `-D warnings` consumers are safe).
#[mcp_client]
pub trait ExampleApi {
    /// Greet someone by name. Returns the greeting text directly.
    async fn greet(&self, name: String) -> stand_in_client::Result<String>;

    /// Add two integers. Uses `#[tool]` to map to the `add` tool
    /// and deserializes the result as `i64` (non-`String` path).
    #[tool(name = "add")]
    async fn add_numbers(&self, a: i64, b: i64) -> stand_in_client::Result<i64>;

    /// Divide two integers. If the divisor is zero, the server returns
    /// `isError: true`, which the typed layer collapses into
    /// `Err(Error::ToolError(...))`.
    async fn divide(&self, a: i64, b: i64) -> stand_in_client::Result<String>;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn free_addr() -> SocketAddr {
    let listener = std::net::TcpListener::bind("127.0.0.1:0").unwrap();
    let addr = listener.local_addr().unwrap();
    drop(listener);
    addr
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

#[tokio::main]
async fn main() {
    println!("=== stand-in-client :: typed client example (macro) ===\n");

    // ── Spawn in-process server ──────────────────────────────────────────

    let addr = free_addr();
    println!("Starting in-process server on http://{addr} ...");

    tokio::spawn(async move {
        TypedExampleServer::serve(stand_in::transport::HttpTransport::new(addr))
            .await
            .unwrap();
    });

    tokio::time::sleep(Duration::from_millis(300)).await;

    // ── Connect dynamic client ───────────────────────────────────────────

    let url = format!("http://{addr}/mcp");
    let client = Client::builder()
        .transport(ClientHttpTransport::new(&url))
        .client_info("typed-example", env!("CARGO_PKG_VERSION"))
        .timeout(Duration::from_secs(10))
        .connect()
        .await
        .expect("Failed to connect");

    println!(
        "Connected to: {} v{}",
        client.server_info().name,
        client.server_info().version
    );
    println!("Tools: {:?}", tool_names(&client));
    println!();

    // ── Wrap in typed client ─────────────────────────────────────────────

    let api = ExampleApiClient::new(client);

    // ── Typed call: greet (String return → text extraction) ──────────────

    println!("── Typed: greet ──");
    let greeting = api.greet("Stand-in".into()).await.unwrap();
    println!("  api.greet(\"Stand-in\") => \"{greeting}\"");

    // ── Typed call: add_numbers (i64 return → from_str deserialization) ──

    println!("── Typed: add_numbers (mapped to 'add' via #[tool]) ──");
    let sum = api.add_numbers(40, 2).await.unwrap();
    println!("  api.add_numbers(40, 2) => {sum} (i64)");

    // ── Typed call: divide (String return, no error) ─────────────────────

    println!("── Typed: divide ──");
    let quotient = api.divide(100, 4).await.unwrap();
    println!("  api.divide(100, 4) => \"{quotient}\"");

    // ── Typed call: divide by zero (isError → ToolError) ─────────────────

    println!("── Typed: divide by zero (isError → ToolError collapse) ──");
    let err = api.divide(10, 0).await.unwrap_err();
    println!("  api.divide(10, 0) => Err(Error::ToolError(\"{err}\"))");
    println!();

    // ── Access inner client + disconnect ─────────────────────────────────

    println!("── Disconnect ──");
    api.into_inner()
        .disconnect()
        .await
        .expect("disconnect should succeed");
    println!("Done.");
}

// ---------------------------------------------------------------------------
// Utilities
// ---------------------------------------------------------------------------

fn tool_names(client: &Client) -> Vec<&str> {
    client.tools().iter().map(|t| t.name.as_str()).collect()
}
